In [1]:
import torch

In [2]:
x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [3]:
x.shape #张量的形状

torch.Size([12])

In [4]:
x.numel() #张量的元素个数

12

In [5]:
X = x.reshape((3,4)) #改变张量形状
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [6]:
zeros = torch.zeros((2, 3, 4)) #全0张量（形状为2*3*4）
print(zeros)
ones = torch.ones((2, 3, 4)) #全1张量（形状为2*3*4）
print(ones)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [7]:
#通过数组创建张量
t = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(t.shape)
print(t)

torch.Size([3, 2, 2])
tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])


In [8]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x**y
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [9]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.arange(12, dtype=torch.float32).reshape((3,4))
Z1 = torch.cat((X,Y), dim=0) #行联结
Z2 = torch.cat((X,Y), dim=1) #列联结
print(Z1)
print(Z2)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.,  0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.,  8.,  9., 10., 11.]])


In [10]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.zeros((3,4))
X == Y #按元素判断是否相同

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [11]:
# sum(): 张量求和
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
s1 = X.sum() #张量按元素求和
s2 = X.sum(0, keepdim=True) #张量按列(轴0)求和, keepdim用于保持矩阵的二维特性
s3 = X.sum(1, keepdim=True) #张量按行(轴1)求和
print('X:', X)
print('sum:', s1)
print('sum(0):', s2)
print('sum(1):', s3)

X: tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
sum: tensor(66.)
sum(0): tensor([[12., 15., 18., 21.]])
sum(1): tensor([[ 6.],
        [22.],
        [38.]])


In [12]:
# 广播机制(broadcasting mechanism): 不同形状的张量运算
# 若x的形状是m_1*m_2*...*m_y*...*m_x, 且y的形状是
# (1) m_y*...*m_x
# (2) 1*m_x
# 则张量x和y可以进行计算

# example1: x(4*2*3),y(1*3)
x = torch.arange(24).reshape((4,2,3))
y = torch.arange(3).reshape((1,3))
print(x)
print(y)
print(x+y)
print(x*y)
# example2: x(4*2*3),y(2*3)
x = torch.arange(24).reshape((4,2,3))
y = torch.arange(3).reshape((3))
print('x:', x)
print('y:', y)
print('x+y:', x+y)
print('x*y:', x*y)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]])
tensor([[0, 1, 2]])
tensor([[[ 0,  2,  4],
         [ 3,  5,  7]],

        [[ 6,  8, 10],
         [ 9, 11, 13]],

        [[12, 14, 16],
         [15, 17, 19]],

        [[18, 20, 22],
         [21, 23, 25]]])
tensor([[[ 0,  1,  4],
         [ 0,  4, 10]],

        [[ 0,  7, 16],
         [ 0, 10, 22]],

        [[ 0, 13, 28],
         [ 0, 16, 34]],

        [[ 0, 19, 40],
         [ 0, 22, 46]]])
x: tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]])
y: tensor([0, 1, 2])
x+y: tensor([[[ 0,  2,  4],
         [ 3,  5,  7]],

        [[ 6,  8, 10],
         [ 9, 11, 13]],

        [[12, 14, 16],
         [15, 17, 19]],

        [[18, 20, 22],
         [21, 23

In [13]:
# 对原始张量的内存执行原地操作
X = torch.arange(12).reshape((3,4))
Y = torch.arange(12).reshape((3,4))
Z = torch.zeros_like(Y)
id_z_ori = id(Z)
Z[:] = X + Y #对每个元素执行操作，不重新存储
id_z_insitu = id(Z)
Z = X + Y #直接执行相加操作，重新存储
id_z_diradd = id(Z)

print(id_z_ori == id_z_insitu, id_z_ori == id_z_diradd)

True False


In [14]:
# 与Numpy张量相互转换
X = torch.arange(12).reshape((3,4))
Y1 = X.numpy() #转换为numpy
Y2 = torch.tensor(Y1)  #转换为tensor
print('numpy:\n', Y1)
print('tensor:\n', Y2)

numpy:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
tensor:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
